### ISSUE TITLE
Remove constants from specs

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#329]
Because they leak into the global scope.

**Comment by xzhflying** [comment]
How about replacing with [Stub Constant](https://www.relishapp.com/rspec/rspec-mocks/v/2-11/docs/stubbing-constants/stub-defined-constant#stub-top-level-constant)

**Comment by lowjoel** [comment]
That's an old version of RSpec.

**Comment by lowjoel** [comment]
class DummyCourseModule
class TestComponent
class SampleModel < ActiveRecord::Base
class SampleController < ActionController::Base; end
class SampleFormBuilder < ActionView::Helpers::FormBuilder; end
class SampleView < ActionView::Base; end
class ActsAsExperiencePointsRecordDummyClass < ActiveRecord::Base
class DummyClass < ActiveRecord::Base

**Comment by lowjoel** [comment]
@allenwq I fixed the acts_as_tenant support helper the other day. I believe that would fix this problem as well. Can you help verify please?

**Comment by allenwq** [comment]
@lowjoel Sorry, which PR ?

**Comment by lowjoel** [comment]
#342. See acts_as_tenant.rb

**Comment by allenwq** [comment]
@lowjoel  Seems like #342  didn't fix this, I can still get warnings if I redefine a constant 

`warning: already initialized constant CONSTANT`
` xxx: : warning: previous definition of CONSTANT was here`

**Comment by lowjoel** [comment]
Example?

**Comment by allenwq** [comment]
Just declare two constants with the same name in two files. And I declared both of them inside `with_tenant`

**Comment by lowjoel** [comment]
This diff allows us to see the delta:

```diff
 spec/rails_helper.rb | 10 ++++++++++
 1 file changed, 10 insertions(+)

diff --git a/spec/rails_helper.rb b/spec/rails_helper.rb
index c116210..d2da2c3 100644
--- a/spec/rails_helper.rb
+++ b/spec/rails_helper.rb
@@ -55,4 +55,14 @@ RSpec.configure do |config|
 
   # Old school have_tag, with_tag(and more) matchers for rspec 3
   config.include RSpecHtmlMatchers
+
+
+  config.after(:suite) do
+    old_constants = Object.instance_variable_get(:@pre_spec_defined_constants)
+    new_constants = Object.constants
+    new = new_constants - old_constants
+    puts new.inspect
+  end
 end
+
+Object.instance_variable_set(:@pre_spec_defined_constants, Object.constants.dup)

```
